server:
  port: 5000

spring:
  application: account-command
  data:
    mongodb:
      host: localhost
      port: 27017
      database: bankAccount
  kafka:
    producer:
      bootstrap-server: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
